### ISSUE TITLE
Revert with automatically generated message is treated as a fix

### ISSUE THREAD

**Issue by PatrykKaczmarek** [netguru/review#36]
<img width="1271" alt="screen shot 2015-08-07 at 10 54 05" src="https://cloud.githubusercontent.com/assets/3520281/9132317/ef5e9ed4-3cf2-11e5-91e9-0aa0da2fee86.png">

**Comment by mamut** [comment]
I'd say it's alright – if it's reverted, then it's like it never existed, so there is nothing to fix

The old app worked the same way
