### ISSUE TITLE
Chrome extension for reviewing

### ISSUE THREAD

**Issue by KillaPL** [netguru/review#4]
Hello

Before your review app was released, we were working on our own, and part of it was chrome extension for reviewing. It simply rendered accept/pass/reject buttons above commits in github: 

![extension](https://f.cloud.github.com/assets/1272828/2309969/fba29bf2-a2dc-11e3-9cbb-60b097864e02.png)

Code for it is available at https://github.com/jdudek/go-review-go/blob/master/extras/chrome/github.js

It would need some polishing and some work to integrate it with your app, but we are willing to do so. 

What do you think?

**Comment by mamut** [comment]
we ended up with writing an extension of our own, but all it does is provide easy search for projects – https://github.com/netguru/review-chrome-extension

we don't have any specific plans for it atm – better API in the review app might make writing browser extensions possible, but their existence is not a direct concern of the app
